name: Build Python Package

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install wheel setuptools twine
          sudo apt-get update
          sudo apt-get install -y xvfb python-opengl ffmpeg python3-libtorrent
      - name: Install Python dependencies
        run: |
          pip install imageio==2.4.1
          pip install --upgrade AutoROM
          AutoROM --accept-license
          pip install gym[atari,accept-rom-license]
          pip install pytest
      - name: Run tests
        run: |
          pytest tests/
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: dist/*
